//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchemaFirstApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_product
    {
        public int Id { get; set; }
        public string productname { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> MFD { get; set; }
        public Nullable<int> catId { get; set; }
    
        public virtual Car_Category Car_Category { get; set; }
    }
}
