//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Example.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Indiancar
    {
        public int carId { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Please the Car Name"), MaxLength(20)]
        [Display(Name = "Cars Name")]
        public string carname { get; set; }

        [DisplayFormat(NullDisplayText = "Brands Not Specified")]
        public string brand { get; set; }
        [Range(20, 30)]
        public string model { get; set; }
        
        public Nullable<decimal> price { get; set; }
        public Nullable<int> Modelyear { get; set; }
    }
}
