//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Example.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MydbEntities1 : DbContext
    {
        public MydbEntities1()
            : base("name=MydbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Indiancar> Indiancars { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<worker> workers { get; set; }
    }
}
