//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Example.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int Roll_no { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> Eng { get; set; }
        public Nullable<int> Maths { get; set; }
        public Nullable<int> sci { get; set; }
    }
}
